### ISSUE TITLE
python good new issue

### ISSUE THREAD

**Issue by coderatul** [coderatul/invoice-generator-python#3]
update my readme my including 
info of modules used in my project

**Comment by ajjayymahato** [comment]
I would like to take up this issue. Is it still open? If yes please assign it to me.

**Comment by coderatul** [comment]
i recently added several features use the project and update readme file 
some features addede are :
1. users can update menu via text file
2. now serial number is used to identify products 
3. now quantuty is also shown againts every iten bought
