### ISSUE TITLE
update documentation (readme.md file) as new features where added

### ISSUE THREAD

**Issue by coderatul** [coderatul/invoice-generator-python#8]
compare current documentation againts the new features added and update readme file 

some new features added where:
- user can update menu using text file
- now quantity againts products are shown 
- serial numbers are used to indenity products 
- many other

**Comment by coderatul** [comment]
@kiozet as you have contributed to this project and have an overall idea , would you like to update documentation

**Comment by kiozet** [comment]
@coderatul sure, I will do this, when I will be at home, buddy:)

**Comment by coderatul** [comment]
> @coderatul sure, I will do this, when I will be at home, buddy:)

ok i am assigning this issue to you
